# --- !Ups
insert into questions (question, subject_id, party_id) values ('In congue. Etiam justo. Etiam pretium iaculis justo.', 1, 6);
insert into questions (question, subject_id, party_id) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 10, 7);
insert into questions (question, subject_id, party_id) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 9, 4);
insert into questions (question, subject_id, party_id) values ('Fusce posuere felis sed lacus.', 10, 9);
insert into questions (question, subject_id, party_id) values ('Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 7, 3);
insert into questions (question, subject_id, party_id) values ('Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 5, 5);
insert into questions (question, subject_id, party_id) values ('In congue. Etiam justo. Etiam pretium iaculis justo.', 6, 10);
insert into questions (question, subject_id, party_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 7, 4);
insert into questions (question, subject_id, party_id) values ('Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue.', 2, 6);
insert into questions (question, subject_id, party_id) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 8, 7);
insert into questions (question, subject_id, party_id) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 9, 2);
insert into questions (question, subject_id, party_id) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 7, 5);
insert into questions (question, subject_id, party_id) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 5, 10);
insert into questions (question, subject_id, party_id) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna.', 4, 4);
insert into questions (question, subject_id, party_id) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 4, 1);
insert into questions (question, subject_id, party_id) values ('Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1, 6);
insert into questions (question, subject_id, party_id) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 9, 8);
insert into questions (question, subject_id, party_id) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 5, 10);
insert into questions (question, subject_id, party_id) values ('Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 3, 6);
insert into questions (question, subject_id, party_id) values ('Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 4, 3);
insert into questions (question, subject_id, party_id) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 6, 4);
insert into questions (question, subject_id, party_id) values ('Phasellus in felis. Donec semper sapien a libero. Nam dui.', 10, 1);
insert into questions (question, subject_id, party_id) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 9, 4);
insert into questions (question, subject_id, party_id) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 9, 8);
insert into questions (question, subject_id, party_id) values ('Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula.', 7, 8);
insert into questions (question, subject_id, party_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 8, 5);
insert into questions (question, subject_id, party_id) values ('Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 1, 5);
insert into questions (question, subject_id, party_id) values ('In congue. Etiam justo. Etiam pretium iaculis justo.', 4, 2);
insert into questions (question, subject_id, party_id) values ('Nullam sit amet turpis elementum ligula vehicula consequat.', 4, 10);
insert into questions (question, subject_id, party_id) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue.', 7, 9);
insert into questions (question, subject_id, party_id) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 10, 5);
insert into questions (question, subject_id, party_id) values ('Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque.', 3, 3);
insert into questions (question, subject_id, party_id) values ('Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis.', 4, 4);
insert into questions (question, subject_id, party_id) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 6, 6);
insert into questions (question, subject_id, party_id) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 10, 1);
insert into questions (question, subject_id, party_id) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 5, 5);
insert into questions (question, subject_id, party_id) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 10, 1);
insert into questions (question, subject_id, party_id) values ('Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget.', 4, 1);
insert into questions (question, subject_id, party_id) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 9, 10);
insert into questions (question, subject_id, party_id) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 6, 4);
insert into questions (question, subject_id, party_id) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 8, 10);
insert into questions (question, subject_id, party_id) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 7, 5);
insert into questions (question, subject_id, party_id) values ('In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices.', 6, 5);
insert into questions (question, subject_id, party_id) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 10, 4);
insert into questions (question, subject_id, party_id) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 6, 6);
insert into questions (question, subject_id, party_id) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 10, 5);
insert into questions (question, subject_id, party_id) values ('In quis justo. Maecenas rhoncus aliquam lacus.', 6, 7);
insert into questions (question, subject_id, party_id) values ('Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 4, 2);
insert into questions (question, subject_id, party_id) values ('Quisque id justo sit amet sapien dignissim vestibulum.', 10, 10);
insert into questions (question, subject_id, party_id) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 4, 7);
insert into questions (question, subject_id, party_id) values ('Curabitur in libero ut massa volutpat convallis. Morbi odio odio.', 5, 9);
insert into questions (question, subject_id, party_id) values ('Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 9, 10);
insert into questions (question, subject_id, party_id) values ('Quisque porta volutpat erat. Quisque erat eros, viverra eget.', 10, 2);
insert into questions (question, subject_id, party_id) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 6, 9);
insert into questions (question, subject_id, party_id) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 8, 3);
insert into questions (question, subject_id, party_id) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 6, 4);
insert into questions (question, subject_id, party_id) values ('Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget.', 7, 9);
insert into questions (question, subject_id, party_id) values ('Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 2, 8);
insert into questions (question, subject_id, party_id) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 2, 8);
insert into questions (question, subject_id, party_id) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 4, 4);
insert into questions (question, subject_id, party_id) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 3, 7);
insert into questions (question, subject_id, party_id) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 2, 3);
insert into questions (question, subject_id, party_id) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 9, 7);
insert into questions (question, subject_id, party_id) values ('Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 4, 10);
insert into questions (question, subject_id, party_id) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 2, 5);
insert into questions (question, subject_id, party_id) values ('Vestibulum ac est lacinia nisi venenatis tristique.', 8, 8);
insert into questions (question, subject_id, party_id) values ('Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 6, 6);
insert into questions (question, subject_id, party_id) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 9, 2);
insert into questions (question, subject_id, party_id) values ('Phasellus in felis. Donec semper sapien a libero. Nam dui.', 7, 5);
insert into questions (question, subject_id, party_id) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 4, 3);
insert into questions (question, subject_id, party_id) values ('Vestibulum ac est lacinia nisi venenatis tristique.', 3, 1);
insert into questions (question, subject_id, party_id) values ('Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 4, 7);
insert into questions (question, subject_id, party_id) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 5, 4);
insert into questions (question, subject_id, party_id) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 3, 4);
insert into questions (question, subject_id, party_id) values ('Fusce consequat. Nulla nisl. Nunc nisl.', 3, 7);
insert into questions (question, subject_id, party_id) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 4, 8);
insert into questions (question, subject_id, party_id) values ('Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 7, 10);
insert into questions (question, subject_id, party_id) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 2, 10);
insert into questions (question, subject_id, party_id) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 3, 1);
insert into questions (question, subject_id, party_id) values ('Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet.', 2, 6);
insert into questions (question, subject_id, party_id) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 7, 9);
insert into questions (question, subject_id, party_id) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 7, 10);
insert into questions (question, subject_id, party_id) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 5, 4);
insert into questions (question, subject_id, party_id) values ('In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis.', 8, 1);
insert into questions (question, subject_id, party_id) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 5, 7);
insert into questions (question, subject_id, party_id) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 6, 8);
insert into questions (question, subject_id, party_id) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 1, 10);
insert into questions (question, subject_id, party_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, 9);
insert into questions (question, subject_id, party_id) values ('Proin interdum mauris non ligula pellentesque ultrices.', 3, 9);
insert into questions (question, subject_id, party_id) values ('Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 9, 8);
insert into questions (question, subject_id, party_id) values ('Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 5, 7);
insert into questions (question, subject_id, party_id) values ('Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 3, 7);
insert into questions (question, subject_id, party_id) values ('In congue. Etiam justo. Etiam pretium iaculis justo.', 2, 6);
insert into questions (question, subject_id, party_id) values ('Quisque id justo sit amet sapien dignissim vestibulum.', 9, 8);
insert into questions (question, subject_id, party_id) values ('Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula.', 4, 9);
insert into questions (question, subject_id, party_id) values ('Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 9, 2);
insert into questions (question, subject_id, party_id) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 4, 1);
insert into questions (question, subject_id, party_id) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna.', 9, 6);
insert into questions (question, subject_id, party_id) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue.', 5, 2);
insert into questions (question, subject_id, party_id) values ( 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, 7);
