insert into users (id, email, passw, age, sex, city, active) values (1, 'ajenkins0@symantec.com', 'pdutmdPW', 79, 'Male', 'Alor Setar', 1);
insert into users (id, email, passw, age, sex, city, active) values (2, 'trose1@indiegogo.com', 'H6yP6qm', 94, 'Male', 'San Felipe', 1);
insert into users (id, email, passw, age, sex, city, active) values (3, 'kcox2@nbcnews.com', '37qAujWI', 56, 'Female', 'Zitong', 1);
insert into users (id, email, passw, age, sex, city, active) values (4, 'jburns3@state.gov', 'OGzLPjqwTDB', 63, 'Male', 'Pilar', 1);
insert into users (id, email, passw, age, sex, city, active) values (5, 'mwood4@howstuffworks.com', 'jtHdvnLcuqJW', 79, 'Female', 'Hāfizābād', 1);
insert into users (id, email, passw, age, sex, city, active) values (6, 'pwatson5@google.it', 'vjE2UuWZW', 52, 'Male', 'Crossmolina', 1);
insert into users (id, email, passw, age, sex, city, active) values (7, 'npowell6@un.org', 'D4YkLtiy7n', 52, 'Female', 'Kinna', 1);
insert into users (id, email, passw, age, sex, city, active) values (8, 'eruiz7@si.edu', '9mJuWFGXJH', 49, 'Male', 'Zamoskvorech’ye', 1);
insert into users (id, email, passw, age, sex, city, active) values (9, 'rstephens8@unc.edu', 'KznQCz1eL3r7', 36, 'Male', 'Krajan', 1);
insert into users (id, email, passw, age, sex, city, active) values (10, 'lburton9@nymag.com', '8oqBB6', 21, 'Male', 'Marvdasht', 1);